/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>
#include <qcustomplot.h>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *client;
    QWidget *Enregistrement;
    QLabel *label_5;
    QLabel *cinsclients;
    QLabel *prenomsclients;
    QLabel *nomsclients;
    QLabel *idproduitsclients;
    QLabel *idclients;
    QLineEdit *EmailClient_3;
    QLabel *emailsclients;
    QLabel *numtelsclients;
    QLabel *adressesclients;
    QLineEdit *PrenomClient_3;
    QLineEdit *NomClient_3;
    QLineEdit *idClient_3;
    QLineEdit *numClient_3;
    QLineEdit *cinClient_3;
    QLineEdit *idProduitClient_3;
    QLineEdit *adresseClient_3;
    QGroupBox *groupBox;
    QPushButton *AjouterClient;
    QWidget *Consultation;
    QTableView *ViewClientAfficher;
    QGroupBox *groupBox_2;
    QPushButton *AfficherClient;
    QWidget *Modification;
    QTableView *ViewClientModifier;
    QGroupBox *groupBox_3;
    QPushButton *RefrachirClientModifier;
    QLabel *idClientt;
    QLineEdit *idClient;
    QLineEdit *numClient;
    QLabel *numtellClient;
    QLineEdit *idProduitClient;
    QLineEdit *EmailClient;
    QLabel *idproduittClient;
    QLabel *emaillClient;
    QLineEdit *NomClient;
    QLabel *nommClient;
    QLineEdit *cinClient;
    QLabel *cinnClient;
    QLineEdit *AdresseClient;
    QLabel *adresseeClient;
    QLineEdit *PrenomClient;
    QLabel *prenommClient;
    QPushButton *ModifierClient;
    QWidget *Suppression;
    QPushButton *SupprimerClient;
    QLabel *id_ClientD;
    QLineEdit *id_clientD;
    QGroupBox *groupBox_5;
    QPushButton *RefrachirClient;
    QTableView *ViewClientSupprimer;
    QWidget *Recherche;
    QTableView *ViewClientRecherche;
    QLabel *id_ClientR_1;
    QPushButton *RechercheClient;
    QLineEdit *id_clientR_2;
    QGroupBox *groupBox_4;
    QWidget *tab;
    QTableView *ViewTriClient;
    QPushButton *trierClient;
    QPushButton *ecxporter_en_pdf_client;
    QGroupBox *groupBox_6;
    QWidget *tab_3;
    QPushButton *statClient;
    QCustomPlot *customPlot;
    QGroupBox *groupBox_7;
    QWidget *tab_2;
    QLineEdit *subject;
    QLineEdit *label_13;
    QLineEdit *label_16;
    QLineEdit *server;
    QLineEdit *label_14;
    QLineEdit *label_15;
    QLineEdit *uname;
    QLineEdit *rcpt;
    QLineEdit *port;
    QLineEdit *paswd;
    QPushButton *sendBtn;
    QTextEdit *msg;
    QTabWidget *client_2;
    QWidget *Enregistrement_2;
    QLabel *label_6;
    QLabel *cinsclients_2;
    QLabel *prenomsclients_2;
    QLabel *nomsclients_2;
    QLabel *idproduitsclients_2;
    QLabel *idclients_2;
    QLineEdit *EmailClient_4;
    QLabel *emailsclients_2;
    QLabel *numtelsclients_2;
    QLabel *adressesclients_2;
    QLineEdit *PrenomClient_4;
    QLineEdit *NomClient_4;
    QLineEdit *idClient_4;
    QLineEdit *numClient_4;
    QLineEdit *cinClient_4;
    QLineEdit *idProduitClient_4;
    QLineEdit *adresseClient_4;
    QGroupBox *groupBox_12;
    QPushButton *AjouterClient_2;
    QWidget *Consultation_2;
    QTableView *ViewClientAfficher_2;
    QGroupBox *groupBox_13;
    QPushButton *AfficherClient_2;
    QWidget *Modification_2;
    QTableView *ViewClientModifier_2;
    QGroupBox *groupBox_14;
    QPushButton *RefrachirClientModifier_2;
    QLabel *idClientt_2;
    QLineEdit *idClient_2;
    QLineEdit *numClient_2;
    QLabel *numtellClient_2;
    QLineEdit *idProduitClient_2;
    QLineEdit *EmailClient_2;
    QLabel *idproduittClient_2;
    QLabel *emaillClient_2;
    QLineEdit *NomClient_2;
    QLabel *nommClient_2;
    QLineEdit *cinClient_2;
    QLabel *cinnClient_2;
    QLineEdit *AdresseClient_2;
    QLabel *adresseeClient_2;
    QLineEdit *PrenomClient_2;
    QLabel *prenommClient_2;
    QPushButton *ModifierClient_2;
    QWidget *Suppression_2;
    QPushButton *SupprimerClient_2;
    QLabel *id_ClientD_2;
    QLineEdit *id_clientD_2;
    QGroupBox *groupBox_15;
    QPushButton *RefrachirClient_2;
    QTableView *ViewClientSupprimer_2;
    QWidget *Recherche_2;
    QTableView *ViewClientRecherche_2;
    QLabel *id_ClientR_2;
    QPushButton *RechercheClient_2;
    QLineEdit *id_clientR_3;
    QGroupBox *groupBox_16;
    QWidget *tab_5;
    QTableView *ViewTriClient_2;
    QPushButton *trierClient_2;
    QPushButton *ecxporter_en_pdf_client_2;
    QGroupBox *groupBox_17;
    QWidget *tab_6;
    QPushButton *statClient_2;
    QCustomPlot *customPlot_2;
    QGroupBox *groupBox_18;
    QWidget *tab_7;
    QPushButton *sendBtn_2;
    QGroupBox *groupBox_11;
    QPushButton *browseBtnClient;
    QLineEdit *fileClient;
    QLineEdit *mail_passClient;
    QLineEdit *rcptClient;
    QTextEdit *msgClient;
    QLineEdit *subjectClient;
    QPushButton *sendBtn_Client;
    QWidget *tab_8;
    QGroupBox *groupBox_19;
    QGroupBox *groupBox_20;
    QPushButton *cameraClient_2;
    QGroupBox *groupBox_21;
    QPushButton *playClient_2;
    QPushButton *stopClient_2;
    QWidget *tab_4;
    QGroupBox *groupBox_8;
    QGroupBox *groupBox_9;
    QPushButton *cameraClient;
    QGroupBox *groupBox_10;
    QPushButton *playClient;
    QPushButton *stopClient;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;
    QMenuBar *menuBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1171, 705);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        client = new QTabWidget(centralWidget);
        client->setObjectName(QStringLiteral("client"));
        client->setGeometry(QRect(30, 20, 1051, 591));
        client->setStyleSheet(QLatin1String("border-color: rgb(0, 255, 255);\n"
"background-color: rgb(255, 255, 255);"));
        Enregistrement = new QWidget();
        Enregistrement->setObjectName(QStringLiteral("Enregistrement"));
        label_5 = new QLabel(Enregistrement);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(170, 330, 56, 16));
        cinsclients = new QLabel(Enregistrement);
        cinsclients->setObjectName(QStringLiteral("cinsclients"));
        cinsclients->setGeometry(QRect(650, 290, 56, 16));
        prenomsclients = new QLabel(Enregistrement);
        prenomsclients->setObjectName(QStringLiteral("prenomsclients"));
        prenomsclients->setGeometry(QRect(50, 290, 71, 20));
        nomsclients = new QLabel(Enregistrement);
        nomsclients->setObjectName(QStringLiteral("nomsclients"));
        nomsclients->setGeometry(QRect(50, 200, 91, 16));
        idproduitsclients = new QLabel(Enregistrement);
        idproduitsclients->setObjectName(QStringLiteral("idproduitsclients"));
        idproduitsclients->setGeometry(QRect(630, 200, 71, 16));
        idclients = new QLabel(Enregistrement);
        idclients->setObjectName(QStringLiteral("idclients"));
        idclients->setGeometry(QRect(50, 120, 81, 16));
        EmailClient_3 = new QLineEdit(Enregistrement);
        EmailClient_3->setObjectName(QStringLiteral("EmailClient_3"));
        EmailClient_3->setGeometry(QRect(160, 360, 181, 31));
        emailsclients = new QLabel(Enregistrement);
        emailsclients->setObjectName(QStringLiteral("emailsclients"));
        emailsclients->setGeometry(QRect(50, 370, 56, 16));
        numtelsclients = new QLabel(Enregistrement);
        numtelsclients->setObjectName(QStringLiteral("numtelsclients"));
        numtelsclients->setGeometry(QRect(640, 360, 56, 16));
        adressesclients = new QLabel(Enregistrement);
        adressesclients->setObjectName(QStringLiteral("adressesclients"));
        adressesclients->setGeometry(QRect(630, 120, 56, 16));
        PrenomClient_3 = new QLineEdit(Enregistrement);
        PrenomClient_3->setObjectName(QStringLiteral("PrenomClient_3"));
        PrenomClient_3->setGeometry(QRect(160, 280, 181, 31));
        NomClient_3 = new QLineEdit(Enregistrement);
        NomClient_3->setObjectName(QStringLiteral("NomClient_3"));
        NomClient_3->setGeometry(QRect(160, 190, 181, 31));
        idClient_3 = new QLineEdit(Enregistrement);
        idClient_3->setObjectName(QStringLiteral("idClient_3"));
        idClient_3->setGeometry(QRect(160, 110, 181, 31));
        numClient_3 = new QLineEdit(Enregistrement);
        numClient_3->setObjectName(QStringLiteral("numClient_3"));
        numClient_3->setGeometry(QRect(740, 350, 181, 31));
        cinClient_3 = new QLineEdit(Enregistrement);
        cinClient_3->setObjectName(QStringLiteral("cinClient_3"));
        cinClient_3->setGeometry(QRect(740, 280, 181, 31));
        idProduitClient_3 = new QLineEdit(Enregistrement);
        idProduitClient_3->setObjectName(QStringLiteral("idProduitClient_3"));
        idProduitClient_3->setGeometry(QRect(740, 190, 181, 31));
        adresseClient_3 = new QLineEdit(Enregistrement);
        adresseClient_3->setObjectName(QStringLiteral("adresseClient_3"));
        adresseClient_3->setGeometry(QRect(740, 110, 181, 31));
        groupBox = new QGroupBox(Enregistrement);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(30, 20, 971, 491));
        AjouterClient = new QPushButton(groupBox);
        AjouterClient->setObjectName(QStringLiteral("AjouterClient"));
        AjouterClient->setGeometry(QRect(800, 420, 121, 31));
        client->addTab(Enregistrement, QString());
        groupBox->raise();
        label_5->raise();
        cinsclients->raise();
        prenomsclients->raise();
        nomsclients->raise();
        idproduitsclients->raise();
        idclients->raise();
        EmailClient_3->raise();
        emailsclients->raise();
        numtelsclients->raise();
        adressesclients->raise();
        PrenomClient_3->raise();
        NomClient_3->raise();
        idClient_3->raise();
        numClient_3->raise();
        cinClient_3->raise();
        idProduitClient_3->raise();
        adresseClient_3->raise();
        Consultation = new QWidget();
        Consultation->setObjectName(QStringLiteral("Consultation"));
        ViewClientAfficher = new QTableView(Consultation);
        ViewClientAfficher->setObjectName(QStringLiteral("ViewClientAfficher"));
        ViewClientAfficher->setGeometry(QRect(30, 90, 991, 421));
        groupBox_2 = new QGroupBox(Consultation);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(19, 20, 1011, 521));
        AfficherClient = new QPushButton(groupBox_2);
        AfficherClient->setObjectName(QStringLiteral("AfficherClient"));
        AfficherClient->setGeometry(QRect(830, 30, 131, 31));
        client->addTab(Consultation, QString());
        groupBox_2->raise();
        ViewClientAfficher->raise();
        Modification = new QWidget();
        Modification->setObjectName(QStringLiteral("Modification"));
        ViewClientModifier = new QTableView(Modification);
        ViewClientModifier->setObjectName(QStringLiteral("ViewClientModifier"));
        ViewClientModifier->setGeometry(QRect(20, 280, 991, 241));
        groupBox_3 = new QGroupBox(Modification);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 19, 1021, 521));
        RefrachirClientModifier = new QPushButton(groupBox_3);
        RefrachirClientModifier->setObjectName(QStringLiteral("RefrachirClientModifier"));
        RefrachirClientModifier->setGeometry(QRect(890, 230, 111, 31));
        idClientt = new QLabel(groupBox_3);
        idClientt->setObjectName(QStringLiteral("idClientt"));
        idClientt->setGeometry(QRect(20, 90, 121, 16));
        idClient = new QLineEdit(groupBox_3);
        idClient->setObjectName(QStringLiteral("idClient"));
        idClient->setGeometry(QRect(170, 80, 131, 31));
        idClient->setStyleSheet(QStringLiteral("QLineEdit (219,199,202)"));
        numClient = new QLineEdit(groupBox_3);
        numClient->setObjectName(QStringLiteral("numClient"));
        numClient->setGeometry(QRect(590, 190, 141, 31));
        numtellClient = new QLabel(groupBox_3);
        numtellClient->setObjectName(QStringLiteral("numtellClient"));
        numtellClient->setGeometry(QRect(500, 190, 71, 20));
        idProduitClient = new QLineEdit(groupBox_3);
        idProduitClient->setObjectName(QStringLiteral("idProduitClient"));
        idProduitClient->setGeometry(QRect(440, 130, 141, 31));
        EmailClient = new QLineEdit(groupBox_3);
        EmailClient->setObjectName(QStringLiteral("EmailClient"));
        EmailClient->setGeometry(QRect(440, 80, 141, 31));
        idproduittClient = new QLabel(groupBox_3);
        idproduittClient->setObjectName(QStringLiteral("idproduittClient"));
        idproduittClient->setGeometry(QRect(330, 140, 71, 16));
        emaillClient = new QLabel(groupBox_3);
        emaillClient->setObjectName(QStringLiteral("emaillClient"));
        emaillClient->setGeometry(QRect(350, 80, 56, 16));
        NomClient = new QLineEdit(groupBox_3);
        NomClient->setObjectName(QStringLiteral("NomClient"));
        NomClient->setGeometry(QRect(440, 30, 141, 31));
        nommClient = new QLabel(groupBox_3);
        nommClient->setObjectName(QStringLiteral("nommClient"));
        nommClient->setGeometry(QRect(350, 40, 71, 16));
        cinClient = new QLineEdit(groupBox_3);
        cinClient->setObjectName(QStringLiteral("cinClient"));
        cinClient->setGeometry(QRect(710, 130, 131, 31));
        cinnClient = new QLabel(groupBox_3);
        cinnClient->setObjectName(QStringLiteral("cinnClient"));
        cinnClient->setGeometry(QRect(630, 130, 56, 21));
        AdresseClient = new QLineEdit(groupBox_3);
        AdresseClient->setObjectName(QStringLiteral("AdresseClient"));
        AdresseClient->setGeometry(QRect(710, 80, 131, 31));
        adresseeClient = new QLabel(groupBox_3);
        adresseeClient->setObjectName(QStringLiteral("adresseeClient"));
        adresseeClient->setGeometry(QRect(630, 80, 56, 21));
        PrenomClient = new QLineEdit(groupBox_3);
        PrenomClient->setObjectName(QStringLiteral("PrenomClient"));
        PrenomClient->setGeometry(QRect(710, 30, 131, 31));
        prenommClient = new QLabel(groupBox_3);
        prenommClient->setObjectName(QStringLiteral("prenommClient"));
        prenommClient->setGeometry(QRect(620, 30, 61, 20));
        ModifierClient = new QPushButton(groupBox_3);
        ModifierClient->setObjectName(QStringLiteral("ModifierClient"));
        ModifierClient->setGeometry(QRect(890, 80, 111, 31));
        client->addTab(Modification, QString());
        groupBox_3->raise();
        ViewClientModifier->raise();
        Suppression = new QWidget();
        Suppression->setObjectName(QStringLiteral("Suppression"));
        SupprimerClient = new QPushButton(Suppression);
        SupprimerClient->setObjectName(QStringLiteral("SupprimerClient"));
        SupprimerClient->setGeometry(QRect(780, 40, 131, 31));
        id_ClientD = new QLabel(Suppression);
        id_ClientD->setObjectName(QStringLiteral("id_ClientD"));
        id_ClientD->setGeometry(QRect(200, 70, 131, 31));
        id_clientD = new QLineEdit(Suppression);
        id_clientD->setObjectName(QStringLiteral("id_clientD"));
        id_clientD->setGeometry(QRect(370, 70, 151, 31));
        groupBox_5 = new QGroupBox(Suppression);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 20, 1021, 511));
        RefrachirClient = new QPushButton(groupBox_5);
        RefrachirClient->setObjectName(QStringLiteral("RefrachirClient"));
        RefrachirClient->setGeometry(QRect(860, 120, 121, 28));
        ViewClientSupprimer = new QTableView(groupBox_5);
        ViewClientSupprimer->setObjectName(QStringLiteral("ViewClientSupprimer"));
        ViewClientSupprimer->setGeometry(QRect(10, 160, 1001, 331));
        client->addTab(Suppression, QString());
        groupBox_5->raise();
        SupprimerClient->raise();
        id_ClientD->raise();
        id_clientD->raise();
        Recherche = new QWidget();
        Recherche->setObjectName(QStringLiteral("Recherche"));
        ViewClientRecherche = new QTableView(Recherche);
        ViewClientRecherche->setObjectName(QStringLiteral("ViewClientRecherche"));
        ViewClientRecherche->setGeometry(QRect(30, 140, 981, 371));
        id_ClientR_1 = new QLabel(Recherche);
        id_ClientR_1->setObjectName(QStringLiteral("id_ClientR_1"));
        id_ClientR_1->setGeometry(QRect(220, 70, 131, 31));
        RechercheClient = new QPushButton(Recherche);
        RechercheClient->setObjectName(QStringLiteral("RechercheClient"));
        RechercheClient->setGeometry(QRect(840, 50, 121, 31));
        id_clientR_2 = new QLineEdit(Recherche);
        id_clientR_2->setObjectName(QStringLiteral("id_clientR_2"));
        id_clientR_2->setGeometry(QRect(380, 70, 151, 31));
        groupBox_4 = new QGroupBox(Recherche);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(20, 10, 1011, 521));
        client->addTab(Recherche, QString());
        groupBox_4->raise();
        ViewClientRecherche->raise();
        id_ClientR_1->raise();
        RechercheClient->raise();
        id_clientR_2->raise();
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        ViewTriClient = new QTableView(tab);
        ViewTriClient->setObjectName(QStringLiteral("ViewTriClient"));
        ViewTriClient->setGeometry(QRect(20, 130, 991, 401));
        trierClient = new QPushButton(tab);
        trierClient->setObjectName(QStringLiteral("trierClient"));
        trierClient->setGeometry(QRect(860, 50, 121, 28));
        ecxporter_en_pdf_client = new QPushButton(tab);
        ecxporter_en_pdf_client->setObjectName(QStringLiteral("ecxporter_en_pdf_client"));
        ecxporter_en_pdf_client->setGeometry(QRect(850, 90, 151, 28));
        groupBox_6 = new QGroupBox(tab);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(10, 10, 1021, 541));
        client->addTab(tab, QString());
        groupBox_6->raise();
        ViewTriClient->raise();
        trierClient->raise();
        ecxporter_en_pdf_client->raise();
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        statClient = new QPushButton(tab_3);
        statClient->setObjectName(QStringLiteral("statClient"));
        statClient->setGeometry(QRect(140, 490, 741, 28));
        customPlot = new QCustomPlot(tab_3);
        customPlot->setObjectName(QStringLiteral("customPlot"));
        customPlot->setGeometry(QRect(30, 50, 961, 421));
        groupBox_7 = new QGroupBox(tab_3);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(10, 20, 1021, 531));
        client->addTab(tab_3, QString());
        groupBox_7->raise();
        statClient->raise();
        customPlot->raise();
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        subject = new QLineEdit(tab_2);
        subject->setObjectName(QStringLiteral("subject"));
        subject->setGeometry(QRect(610, 390, 961, 31));
        label_13 = new QLineEdit(tab_2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(650, 140, 113, 22));
        label_16 = new QLineEdit(tab_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(650, 270, 113, 22));
        server = new QLineEdit(tab_2);
        server->setObjectName(QStringLiteral("server"));
        server->setGeometry(QRect(900, 140, 241, 31));
        label_14 = new QLineEdit(tab_2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(650, 190, 113, 22));
        label_15 = new QLineEdit(tab_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(650, 230, 113, 22));
        uname = new QLineEdit(tab_2);
        uname->setObjectName(QStringLiteral("uname"));
        uname->setGeometry(QRect(900, 220, 241, 31));
        rcpt = new QLineEdit(tab_2);
        rcpt->setObjectName(QStringLiteral("rcpt"));
        rcpt->setGeometry(QRect(610, 340, 961, 31));
        port = new QLineEdit(tab_2);
        port->setObjectName(QStringLiteral("port"));
        port->setGeometry(QRect(900, 180, 241, 31));
        paswd = new QLineEdit(tab_2);
        paswd->setObjectName(QStringLiteral("paswd"));
        paswd->setGeometry(QRect(900, 260, 241, 31));
        sendBtn = new QPushButton(tab_2);
        sendBtn->setObjectName(QStringLiteral("sendBtn"));
        sendBtn->setGeometry(QRect(1310, 200, 161, 31));
        msg = new QTextEdit(tab_2);
        msg->setObjectName(QStringLiteral("msg"));
        msg->setGeometry(QRect(610, 430, 971, 241));
        client_2 = new QTabWidget(tab_2);
        client_2->setObjectName(QStringLiteral("client_2"));
        client_2->setGeometry(QRect(0, -20, 1091, 601));
        client_2->setStyleSheet(QLatin1String("border-color: rgb(0, 255, 255);\n"
"background-color: rgb(255, 255, 255);"));
        Enregistrement_2 = new QWidget();
        Enregistrement_2->setObjectName(QStringLiteral("Enregistrement_2"));
        label_6 = new QLabel(Enregistrement_2);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(170, 330, 56, 16));
        cinsclients_2 = new QLabel(Enregistrement_2);
        cinsclients_2->setObjectName(QStringLiteral("cinsclients_2"));
        cinsclients_2->setGeometry(QRect(650, 290, 56, 16));
        prenomsclients_2 = new QLabel(Enregistrement_2);
        prenomsclients_2->setObjectName(QStringLiteral("prenomsclients_2"));
        prenomsclients_2->setGeometry(QRect(50, 290, 71, 20));
        nomsclients_2 = new QLabel(Enregistrement_2);
        nomsclients_2->setObjectName(QStringLiteral("nomsclients_2"));
        nomsclients_2->setGeometry(QRect(50, 200, 91, 16));
        idproduitsclients_2 = new QLabel(Enregistrement_2);
        idproduitsclients_2->setObjectName(QStringLiteral("idproduitsclients_2"));
        idproduitsclients_2->setGeometry(QRect(630, 200, 71, 16));
        idclients_2 = new QLabel(Enregistrement_2);
        idclients_2->setObjectName(QStringLiteral("idclients_2"));
        idclients_2->setGeometry(QRect(50, 120, 81, 16));
        EmailClient_4 = new QLineEdit(Enregistrement_2);
        EmailClient_4->setObjectName(QStringLiteral("EmailClient_4"));
        EmailClient_4->setGeometry(QRect(160, 360, 181, 31));
        emailsclients_2 = new QLabel(Enregistrement_2);
        emailsclients_2->setObjectName(QStringLiteral("emailsclients_2"));
        emailsclients_2->setGeometry(QRect(50, 370, 56, 16));
        numtelsclients_2 = new QLabel(Enregistrement_2);
        numtelsclients_2->setObjectName(QStringLiteral("numtelsclients_2"));
        numtelsclients_2->setGeometry(QRect(640, 360, 56, 16));
        adressesclients_2 = new QLabel(Enregistrement_2);
        adressesclients_2->setObjectName(QStringLiteral("adressesclients_2"));
        adressesclients_2->setGeometry(QRect(630, 120, 56, 16));
        PrenomClient_4 = new QLineEdit(Enregistrement_2);
        PrenomClient_4->setObjectName(QStringLiteral("PrenomClient_4"));
        PrenomClient_4->setGeometry(QRect(160, 280, 181, 31));
        NomClient_4 = new QLineEdit(Enregistrement_2);
        NomClient_4->setObjectName(QStringLiteral("NomClient_4"));
        NomClient_4->setGeometry(QRect(160, 190, 181, 31));
        idClient_4 = new QLineEdit(Enregistrement_2);
        idClient_4->setObjectName(QStringLiteral("idClient_4"));
        idClient_4->setGeometry(QRect(160, 110, 181, 31));
        numClient_4 = new QLineEdit(Enregistrement_2);
        numClient_4->setObjectName(QStringLiteral("numClient_4"));
        numClient_4->setGeometry(QRect(740, 350, 181, 31));
        cinClient_4 = new QLineEdit(Enregistrement_2);
        cinClient_4->setObjectName(QStringLiteral("cinClient_4"));
        cinClient_4->setGeometry(QRect(740, 280, 181, 31));
        idProduitClient_4 = new QLineEdit(Enregistrement_2);
        idProduitClient_4->setObjectName(QStringLiteral("idProduitClient_4"));
        idProduitClient_4->setGeometry(QRect(740, 190, 181, 31));
        adresseClient_4 = new QLineEdit(Enregistrement_2);
        adresseClient_4->setObjectName(QStringLiteral("adresseClient_4"));
        adresseClient_4->setGeometry(QRect(740, 110, 181, 31));
        groupBox_12 = new QGroupBox(Enregistrement_2);
        groupBox_12->setObjectName(QStringLiteral("groupBox_12"));
        groupBox_12->setGeometry(QRect(30, 20, 971, 491));
        AjouterClient_2 = new QPushButton(groupBox_12);
        AjouterClient_2->setObjectName(QStringLiteral("AjouterClient_2"));
        AjouterClient_2->setGeometry(QRect(800, 420, 121, 31));
        client_2->addTab(Enregistrement_2, QString());
        Consultation_2 = new QWidget();
        Consultation_2->setObjectName(QStringLiteral("Consultation_2"));
        ViewClientAfficher_2 = new QTableView(Consultation_2);
        ViewClientAfficher_2->setObjectName(QStringLiteral("ViewClientAfficher_2"));
        ViewClientAfficher_2->setGeometry(QRect(30, 90, 991, 421));
        groupBox_13 = new QGroupBox(Consultation_2);
        groupBox_13->setObjectName(QStringLiteral("groupBox_13"));
        groupBox_13->setGeometry(QRect(19, 20, 1011, 521));
        AfficherClient_2 = new QPushButton(groupBox_13);
        AfficherClient_2->setObjectName(QStringLiteral("AfficherClient_2"));
        AfficherClient_2->setGeometry(QRect(830, 30, 131, 31));
        client_2->addTab(Consultation_2, QString());
        Modification_2 = new QWidget();
        Modification_2->setObjectName(QStringLiteral("Modification_2"));
        ViewClientModifier_2 = new QTableView(Modification_2);
        ViewClientModifier_2->setObjectName(QStringLiteral("ViewClientModifier_2"));
        ViewClientModifier_2->setGeometry(QRect(20, 280, 991, 241));
        groupBox_14 = new QGroupBox(Modification_2);
        groupBox_14->setObjectName(QStringLiteral("groupBox_14"));
        groupBox_14->setGeometry(QRect(10, 19, 1021, 521));
        RefrachirClientModifier_2 = new QPushButton(groupBox_14);
        RefrachirClientModifier_2->setObjectName(QStringLiteral("RefrachirClientModifier_2"));
        RefrachirClientModifier_2->setGeometry(QRect(890, 230, 111, 31));
        idClientt_2 = new QLabel(groupBox_14);
        idClientt_2->setObjectName(QStringLiteral("idClientt_2"));
        idClientt_2->setGeometry(QRect(20, 90, 121, 16));
        idClient_2 = new QLineEdit(groupBox_14);
        idClient_2->setObjectName(QStringLiteral("idClient_2"));
        idClient_2->setGeometry(QRect(170, 80, 131, 31));
        idClient_2->setStyleSheet(QStringLiteral("QLineEdit (219,199,202)"));
        numClient_2 = new QLineEdit(groupBox_14);
        numClient_2->setObjectName(QStringLiteral("numClient_2"));
        numClient_2->setGeometry(QRect(590, 190, 141, 31));
        numtellClient_2 = new QLabel(groupBox_14);
        numtellClient_2->setObjectName(QStringLiteral("numtellClient_2"));
        numtellClient_2->setGeometry(QRect(500, 190, 71, 20));
        idProduitClient_2 = new QLineEdit(groupBox_14);
        idProduitClient_2->setObjectName(QStringLiteral("idProduitClient_2"));
        idProduitClient_2->setGeometry(QRect(440, 130, 141, 31));
        EmailClient_2 = new QLineEdit(groupBox_14);
        EmailClient_2->setObjectName(QStringLiteral("EmailClient_2"));
        EmailClient_2->setGeometry(QRect(440, 80, 141, 31));
        idproduittClient_2 = new QLabel(groupBox_14);
        idproduittClient_2->setObjectName(QStringLiteral("idproduittClient_2"));
        idproduittClient_2->setGeometry(QRect(330, 140, 71, 16));
        emaillClient_2 = new QLabel(groupBox_14);
        emaillClient_2->setObjectName(QStringLiteral("emaillClient_2"));
        emaillClient_2->setGeometry(QRect(350, 80, 56, 16));
        NomClient_2 = new QLineEdit(groupBox_14);
        NomClient_2->setObjectName(QStringLiteral("NomClient_2"));
        NomClient_2->setGeometry(QRect(440, 30, 141, 31));
        nommClient_2 = new QLabel(groupBox_14);
        nommClient_2->setObjectName(QStringLiteral("nommClient_2"));
        nommClient_2->setGeometry(QRect(350, 40, 71, 16));
        cinClient_2 = new QLineEdit(groupBox_14);
        cinClient_2->setObjectName(QStringLiteral("cinClient_2"));
        cinClient_2->setGeometry(QRect(710, 130, 131, 31));
        cinnClient_2 = new QLabel(groupBox_14);
        cinnClient_2->setObjectName(QStringLiteral("cinnClient_2"));
        cinnClient_2->setGeometry(QRect(630, 130, 56, 21));
        AdresseClient_2 = new QLineEdit(groupBox_14);
        AdresseClient_2->setObjectName(QStringLiteral("AdresseClient_2"));
        AdresseClient_2->setGeometry(QRect(710, 80, 131, 31));
        adresseeClient_2 = new QLabel(groupBox_14);
        adresseeClient_2->setObjectName(QStringLiteral("adresseeClient_2"));
        adresseeClient_2->setGeometry(QRect(630, 80, 56, 21));
        PrenomClient_2 = new QLineEdit(groupBox_14);
        PrenomClient_2->setObjectName(QStringLiteral("PrenomClient_2"));
        PrenomClient_2->setGeometry(QRect(710, 30, 131, 31));
        prenommClient_2 = new QLabel(groupBox_14);
        prenommClient_2->setObjectName(QStringLiteral("prenommClient_2"));
        prenommClient_2->setGeometry(QRect(620, 30, 61, 20));
        ModifierClient_2 = new QPushButton(groupBox_14);
        ModifierClient_2->setObjectName(QStringLiteral("ModifierClient_2"));
        ModifierClient_2->setGeometry(QRect(890, 80, 111, 31));
        client_2->addTab(Modification_2, QString());
        Suppression_2 = new QWidget();
        Suppression_2->setObjectName(QStringLiteral("Suppression_2"));
        SupprimerClient_2 = new QPushButton(Suppression_2);
        SupprimerClient_2->setObjectName(QStringLiteral("SupprimerClient_2"));
        SupprimerClient_2->setGeometry(QRect(780, 40, 131, 31));
        id_ClientD_2 = new QLabel(Suppression_2);
        id_ClientD_2->setObjectName(QStringLiteral("id_ClientD_2"));
        id_ClientD_2->setGeometry(QRect(200, 70, 131, 31));
        id_clientD_2 = new QLineEdit(Suppression_2);
        id_clientD_2->setObjectName(QStringLiteral("id_clientD_2"));
        id_clientD_2->setGeometry(QRect(370, 70, 151, 31));
        groupBox_15 = new QGroupBox(Suppression_2);
        groupBox_15->setObjectName(QStringLiteral("groupBox_15"));
        groupBox_15->setGeometry(QRect(10, 20, 1021, 511));
        RefrachirClient_2 = new QPushButton(groupBox_15);
        RefrachirClient_2->setObjectName(QStringLiteral("RefrachirClient_2"));
        RefrachirClient_2->setGeometry(QRect(860, 120, 121, 28));
        ViewClientSupprimer_2 = new QTableView(groupBox_15);
        ViewClientSupprimer_2->setObjectName(QStringLiteral("ViewClientSupprimer_2"));
        ViewClientSupprimer_2->setGeometry(QRect(10, 160, 1001, 331));
        client_2->addTab(Suppression_2, QString());
        Recherche_2 = new QWidget();
        Recherche_2->setObjectName(QStringLiteral("Recherche_2"));
        ViewClientRecherche_2 = new QTableView(Recherche_2);
        ViewClientRecherche_2->setObjectName(QStringLiteral("ViewClientRecherche_2"));
        ViewClientRecherche_2->setGeometry(QRect(30, 140, 981, 371));
        id_ClientR_2 = new QLabel(Recherche_2);
        id_ClientR_2->setObjectName(QStringLiteral("id_ClientR_2"));
        id_ClientR_2->setGeometry(QRect(220, 70, 131, 31));
        RechercheClient_2 = new QPushButton(Recherche_2);
        RechercheClient_2->setObjectName(QStringLiteral("RechercheClient_2"));
        RechercheClient_2->setGeometry(QRect(840, 50, 121, 31));
        id_clientR_3 = new QLineEdit(Recherche_2);
        id_clientR_3->setObjectName(QStringLiteral("id_clientR_3"));
        id_clientR_3->setGeometry(QRect(380, 70, 151, 31));
        groupBox_16 = new QGroupBox(Recherche_2);
        groupBox_16->setObjectName(QStringLiteral("groupBox_16"));
        groupBox_16->setGeometry(QRect(20, 10, 1011, 521));
        client_2->addTab(Recherche_2, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        ViewTriClient_2 = new QTableView(tab_5);
        ViewTriClient_2->setObjectName(QStringLiteral("ViewTriClient_2"));
        ViewTriClient_2->setGeometry(QRect(20, 130, 991, 401));
        trierClient_2 = new QPushButton(tab_5);
        trierClient_2->setObjectName(QStringLiteral("trierClient_2"));
        trierClient_2->setGeometry(QRect(860, 50, 121, 28));
        ecxporter_en_pdf_client_2 = new QPushButton(tab_5);
        ecxporter_en_pdf_client_2->setObjectName(QStringLiteral("ecxporter_en_pdf_client_2"));
        ecxporter_en_pdf_client_2->setGeometry(QRect(850, 90, 151, 28));
        groupBox_17 = new QGroupBox(tab_5);
        groupBox_17->setObjectName(QStringLiteral("groupBox_17"));
        groupBox_17->setGeometry(QRect(10, 10, 1021, 541));
        client_2->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        statClient_2 = new QPushButton(tab_6);
        statClient_2->setObjectName(QStringLiteral("statClient_2"));
        statClient_2->setGeometry(QRect(140, 490, 741, 28));
        customPlot_2 = new QCustomPlot(tab_6);
        customPlot_2->setObjectName(QStringLiteral("customPlot_2"));
        customPlot_2->setGeometry(QRect(30, 50, 961, 421));
        groupBox_18 = new QGroupBox(tab_6);
        groupBox_18->setObjectName(QStringLiteral("groupBox_18"));
        groupBox_18->setGeometry(QRect(10, 20, 1021, 531));
        client_2->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        sendBtn_2 = new QPushButton(tab_7);
        sendBtn_2->setObjectName(QStringLiteral("sendBtn_2"));
        sendBtn_2->setGeometry(QRect(1310, 200, 161, 31));
        groupBox_11 = new QGroupBox(tab_7);
        groupBox_11->setObjectName(QStringLiteral("groupBox_11"));
        groupBox_11->setGeometry(QRect(10, 0, 1031, 541));
        browseBtnClient = new QPushButton(groupBox_11);
        browseBtnClient->setObjectName(QStringLiteral("browseBtnClient"));
        browseBtnClient->setGeometry(QRect(940, 120, 81, 31));
        fileClient = new QLineEdit(groupBox_11);
        fileClient->setObjectName(QStringLiteral("fileClient"));
        fileClient->setGeometry(QRect(50, 140, 881, 31));
        mail_passClient = new QLineEdit(groupBox_11);
        mail_passClient->setObjectName(QStringLiteral("mail_passClient"));
        mail_passClient->setGeometry(QRect(750, 50, 261, 31));
        mail_passClient->setEchoMode(QLineEdit::Password);
        rcptClient = new QLineEdit(groupBox_11);
        rcptClient->setObjectName(QStringLiteral("rcptClient"));
        rcptClient->setGeometry(QRect(50, 50, 691, 31));
        msgClient = new QTextEdit(groupBox_11);
        msgClient->setObjectName(QStringLiteral("msgClient"));
        msgClient->setGeometry(QRect(30, 180, 971, 281));
        subjectClient = new QLineEdit(groupBox_11);
        subjectClient->setObjectName(QStringLiteral("subjectClient"));
        subjectClient->setGeometry(QRect(50, 100, 881, 31));
        sendBtn_Client = new QPushButton(groupBox_11);
        sendBtn_Client->setObjectName(QStringLiteral("sendBtn_Client"));
        sendBtn_Client->setGeometry(QRect(30, 480, 971, 31));
        mail_passClient->raise();
        msgClient->raise();
        subjectClient->raise();
        fileClient->raise();
        rcptClient->raise();
        browseBtnClient->raise();
        sendBtn_Client->raise();
        client_2->addTab(tab_7, QString());
        groupBox_11->raise();
        sendBtn_2->raise();
        tab_8 = new QWidget();
        tab_8->setObjectName(QStringLiteral("tab_8"));
        groupBox_19 = new QGroupBox(tab_8);
        groupBox_19->setObjectName(QStringLiteral("groupBox_19"));
        groupBox_19->setGeometry(QRect(30, 30, 991, 511));
        groupBox_20 = new QGroupBox(groupBox_19);
        groupBox_20->setObjectName(QStringLiteral("groupBox_20"));
        groupBox_20->setGeometry(QRect(400, 110, 231, 101));
        cameraClient_2 = new QPushButton(groupBox_20);
        cameraClient_2->setObjectName(QStringLiteral("cameraClient_2"));
        cameraClient_2->setGeometry(QRect(70, 40, 93, 28));
        groupBox_21 = new QGroupBox(groupBox_19);
        groupBox_21->setObjectName(QStringLiteral("groupBox_21"));
        groupBox_21->setGeometry(QRect(190, 300, 631, 121));
        playClient_2 = new QPushButton(groupBox_21);
        playClient_2->setObjectName(QStringLiteral("playClient_2"));
        playClient_2->setGeometry(QRect(100, 60, 93, 28));
        stopClient_2 = new QPushButton(groupBox_21);
        stopClient_2->setObjectName(QStringLiteral("stopClient_2"));
        stopClient_2->setGeometry(QRect(440, 60, 93, 28));
        client_2->addTab(tab_8, QString());
        client->addTab(tab_2, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        groupBox_8 = new QGroupBox(tab_4);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(30, 30, 991, 511));
        groupBox_9 = new QGroupBox(groupBox_8);
        groupBox_9->setObjectName(QStringLiteral("groupBox_9"));
        groupBox_9->setGeometry(QRect(400, 110, 231, 101));
        cameraClient = new QPushButton(groupBox_9);
        cameraClient->setObjectName(QStringLiteral("cameraClient"));
        cameraClient->setGeometry(QRect(70, 40, 93, 28));
        groupBox_10 = new QGroupBox(groupBox_8);
        groupBox_10->setObjectName(QStringLiteral("groupBox_10"));
        groupBox_10->setGeometry(QRect(190, 300, 631, 121));
        playClient = new QPushButton(groupBox_10);
        playClient->setObjectName(QStringLiteral("playClient"));
        playClient->setGeometry(QRect(100, 60, 93, 28));
        stopClient = new QPushButton(groupBox_10);
        stopClient->setObjectName(QStringLiteral("stopClient"));
        stopClient->setGeometry(QRect(440, 60, 93, 28));
        client->addTab(tab_4, QString());
        MainWindow->setCentralWidget(centralWidget);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1171, 26));
        MainWindow->setMenuBar(menuBar);

        retranslateUi(MainWindow);

        client->setCurrentIndex(2);
        client_2->setCurrentIndex(7);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Gestion des Clients", Q_NULLPTR));
        label_5->setText(QString());
        cinsclients->setText(QApplication::translate("MainWindow", "Cin", Q_NULLPTR));
        prenomsclients->setText(QApplication::translate("MainWindow", "Pr\303\251nom", Q_NULLPTR));
        nomsclients->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        idproduitsclients->setText(QApplication::translate("MainWindow", "id_produit", Q_NULLPTR));
        idclients->setText(QApplication::translate("MainWindow", "ID_Client", Q_NULLPTR));
        EmailClient_3->setPlaceholderText(QApplication::translate("MainWindow", "nom.pr\303\251nom@gmail.com", Q_NULLPTR));
        emailsclients->setText(QApplication::translate("MainWindow", "Email", Q_NULLPTR));
        numtelsclients->setText(QApplication::translate("MainWindow", "Num_Tel", Q_NULLPTR));
        adressesclients->setText(QApplication::translate("MainWindow", "Adresse", Q_NULLPTR));
        PrenomClient_3->setPlaceholderText(QApplication::translate("MainWindow", "Vore pr\303\251nom", Q_NULLPTR));
        NomClient_3->setPlaceholderText(QApplication::translate("MainWindow", "Votre nom", Q_NULLPTR));
        idClient_3->setPlaceholderText(QApplication::translate("MainWindow", "8 chiffres ", Q_NULLPTR));
        numClient_3->setPlaceholderText(QApplication::translate("MainWindow", "8 chiffres ", Q_NULLPTR));
        cinClient_3->setPlaceholderText(QApplication::translate("MainWindow", "8 chiffres ", Q_NULLPTR));
        idProduitClient_3->setPlaceholderText(QApplication::translate("MainWindow", "2A30", Q_NULLPTR));
        adresseClient_3->setPlaceholderText(QApplication::translate("MainWindow", "pays, ville, code postale", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("MainWindow", "Ajouter les informations d'un Client : ", Q_NULLPTR));
        AjouterClient->setText(QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        client->setTabText(client->indexOf(Enregistrement), QApplication::translate("MainWindow", "Enregistrement", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Afficher les informations d'un Client :", Q_NULLPTR));
        AfficherClient->setText(QApplication::translate("MainWindow", "Afficher", Q_NULLPTR));
        client->setTabText(client->indexOf(Consultation), QApplication::translate("MainWindow", "Consultation", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "Modifier les informations d'un Client :", Q_NULLPTR));
        RefrachirClientModifier->setText(QApplication::translate("MainWindow", "R\303\251frachir", Q_NULLPTR));
        idClientt->setText(QApplication::translate("MainWindow", " ID_Client a modifi\303\251e", Q_NULLPTR));
        numtellClient->setText(QApplication::translate("MainWindow", "Num_Tel", Q_NULLPTR));
        idproduittClient->setText(QApplication::translate("MainWindow", "id_produit", Q_NULLPTR));
        emaillClient->setText(QApplication::translate("MainWindow", "Email", Q_NULLPTR));
        nommClient->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        cinnClient->setText(QApplication::translate("MainWindow", " Cin", Q_NULLPTR));
        adresseeClient->setText(QApplication::translate("MainWindow", "Adresse", Q_NULLPTR));
        prenommClient->setText(QApplication::translate("MainWindow", "Pr\303\251nom", Q_NULLPTR));
        ModifierClient->setText(QApplication::translate("MainWindow", "Modifier", Q_NULLPTR));
        client->setTabText(client->indexOf(Modification), QApplication::translate("MainWindow", "Modification", Q_NULLPTR));
        SupprimerClient->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        id_ClientD->setText(QApplication::translate("MainWindow", "ID_Client a supprim\303\251e", Q_NULLPTR));
        id_clientD->setPlaceholderText(QString());
        groupBox_5->setTitle(QApplication::translate("MainWindow", "Supprimer le Client :", Q_NULLPTR));
        RefrachirClient->setText(QApplication::translate("MainWindow", "R\303\251frachir", Q_NULLPTR));
        client->setTabText(client->indexOf(Suppression), QApplication::translate("MainWindow", "Suppression", Q_NULLPTR));
        id_ClientR_1->setText(QApplication::translate("MainWindow", "ID_Client a cherche\303\251", Q_NULLPTR));
        RechercheClient->setText(QApplication::translate("MainWindow", "Recherche", Q_NULLPTR));
        id_clientR_2->setPlaceholderText(QString());
        groupBox_4->setTitle(QApplication::translate("MainWindow", "Chercher un Client :", Q_NULLPTR));
        client->setTabText(client->indexOf(Recherche), QApplication::translate("MainWindow", "Recherche", Q_NULLPTR));
        trierClient->setText(QApplication::translate("MainWindow", "Trier", Q_NULLPTR));
        ecxporter_en_pdf_client->setText(QApplication::translate("MainWindow", "Exporter en Pdf", Q_NULLPTR));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "Trier Client :", Q_NULLPTR));
        client->setTabText(client->indexOf(tab), QApplication::translate("MainWindow", "Trier", Q_NULLPTR));
        statClient->setText(QApplication::translate("MainWindow", "executer statistique", Q_NULLPTR));
        groupBox_7->setTitle(QApplication::translate("MainWindow", "Statistique :", Q_NULLPTR));
        client->setTabText(client->indexOf(tab_3), QApplication::translate("MainWindow", "Statistique", Q_NULLPTR));
        subject->setText(QString());
        subject->setPlaceholderText(QApplication::translate("MainWindow", "object ", Q_NULLPTR));
        label_13->setText(QApplication::translate("MainWindow", "smtp-server ", Q_NULLPTR));
        label_16->setText(QApplication::translate("MainWindow", "password", Q_NULLPTR));
        server->setText(QApplication::translate("MainWindow", "smtp.gmail.com", Q_NULLPTR));
        server->setPlaceholderText(QString());
        label_14->setText(QApplication::translate("MainWindow", "server post ", Q_NULLPTR));
        label_15->setText(QApplication::translate("MainWindow", "user name", Q_NULLPTR));
        uname->setText(QString());
        uname->setPlaceholderText(QString());
        rcpt->setText(QString());
        rcpt->setPlaceholderText(QApplication::translate("MainWindow", "adresse mail", Q_NULLPTR));
        port->setText(QApplication::translate("MainWindow", "465", Q_NULLPTR));
        port->setPlaceholderText(QApplication::translate("MainWindow", "subject", Q_NULLPTR));
        paswd->setText(QString());
        paswd->setPlaceholderText(QString());
        sendBtn->setText(QApplication::translate("MainWindow", "Send", Q_NULLPTR));
        msg->setPlaceholderText(QApplication::translate("MainWindow", "type your message here ...", Q_NULLPTR));
        label_6->setText(QString());
        cinsclients_2->setText(QApplication::translate("MainWindow", "Cin", Q_NULLPTR));
        prenomsclients_2->setText(QApplication::translate("MainWindow", "Pr\303\251nom", Q_NULLPTR));
        nomsclients_2->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        idproduitsclients_2->setText(QApplication::translate("MainWindow", "id_produit", Q_NULLPTR));
        idclients_2->setText(QApplication::translate("MainWindow", "ID_Client", Q_NULLPTR));
        EmailClient_4->setPlaceholderText(QApplication::translate("MainWindow", "nom.pr\303\251nom@gmail.com", Q_NULLPTR));
        emailsclients_2->setText(QApplication::translate("MainWindow", "Email", Q_NULLPTR));
        numtelsclients_2->setText(QApplication::translate("MainWindow", "Num_Tel", Q_NULLPTR));
        adressesclients_2->setText(QApplication::translate("MainWindow", "Adresse", Q_NULLPTR));
        PrenomClient_4->setPlaceholderText(QApplication::translate("MainWindow", "Vore pr\303\251nom", Q_NULLPTR));
        NomClient_4->setPlaceholderText(QApplication::translate("MainWindow", "Votre nom", Q_NULLPTR));
        idClient_4->setPlaceholderText(QApplication::translate("MainWindow", "8 chiffres ", Q_NULLPTR));
        numClient_4->setPlaceholderText(QApplication::translate("MainWindow", "8 chiffres ", Q_NULLPTR));
        cinClient_4->setPlaceholderText(QApplication::translate("MainWindow", "8 chiffres ", Q_NULLPTR));
        idProduitClient_4->setPlaceholderText(QApplication::translate("MainWindow", "2A30", Q_NULLPTR));
        adresseClient_4->setPlaceholderText(QApplication::translate("MainWindow", "pays, ville, code postale", Q_NULLPTR));
        groupBox_12->setTitle(QApplication::translate("MainWindow", "Ajouter les informations d'un Client : ", Q_NULLPTR));
        AjouterClient_2->setText(QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        client_2->setTabText(client_2->indexOf(Enregistrement_2), QApplication::translate("MainWindow", "Enregistrement", Q_NULLPTR));
        groupBox_13->setTitle(QApplication::translate("MainWindow", "Afficher les informations d'un Client :", Q_NULLPTR));
        AfficherClient_2->setText(QApplication::translate("MainWindow", "Afficher", Q_NULLPTR));
        client_2->setTabText(client_2->indexOf(Consultation_2), QApplication::translate("MainWindow", "Consultation", Q_NULLPTR));
        groupBox_14->setTitle(QApplication::translate("MainWindow", "Modifier les informations d'un Client :", Q_NULLPTR));
        RefrachirClientModifier_2->setText(QApplication::translate("MainWindow", "R\303\251frachir", Q_NULLPTR));
        idClientt_2->setText(QApplication::translate("MainWindow", " ID_Client a modifi\303\251e", Q_NULLPTR));
        numtellClient_2->setText(QApplication::translate("MainWindow", "Num_Tel", Q_NULLPTR));
        idproduittClient_2->setText(QApplication::translate("MainWindow", "id_produit", Q_NULLPTR));
        emaillClient_2->setText(QApplication::translate("MainWindow", "Email", Q_NULLPTR));
        nommClient_2->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        cinnClient_2->setText(QApplication::translate("MainWindow", " Cin", Q_NULLPTR));
        adresseeClient_2->setText(QApplication::translate("MainWindow", "Adresse", Q_NULLPTR));
        prenommClient_2->setText(QApplication::translate("MainWindow", "Pr\303\251nom", Q_NULLPTR));
        ModifierClient_2->setText(QApplication::translate("MainWindow", "Modifier", Q_NULLPTR));
        client_2->setTabText(client_2->indexOf(Modification_2), QApplication::translate("MainWindow", "Modification", Q_NULLPTR));
        SupprimerClient_2->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        id_ClientD_2->setText(QApplication::translate("MainWindow", "ID_Client a supprim\303\251e", Q_NULLPTR));
        id_clientD_2->setPlaceholderText(QString());
        groupBox_15->setTitle(QApplication::translate("MainWindow", "Supprimer le Client :", Q_NULLPTR));
        RefrachirClient_2->setText(QApplication::translate("MainWindow", "R\303\251frachir", Q_NULLPTR));
        client_2->setTabText(client_2->indexOf(Suppression_2), QApplication::translate("MainWindow", "Suppression", Q_NULLPTR));
        id_ClientR_2->setText(QApplication::translate("MainWindow", "ID_Client a cherche\303\251", Q_NULLPTR));
        RechercheClient_2->setText(QApplication::translate("MainWindow", "Recherche", Q_NULLPTR));
        id_clientR_3->setPlaceholderText(QString());
        groupBox_16->setTitle(QApplication::translate("MainWindow", "Chercher un Client :", Q_NULLPTR));
        client_2->setTabText(client_2->indexOf(Recherche_2), QApplication::translate("MainWindow", "Recherche", Q_NULLPTR));
        trierClient_2->setText(QApplication::translate("MainWindow", "Trier", Q_NULLPTR));
        ecxporter_en_pdf_client_2->setText(QApplication::translate("MainWindow", "Exporter en Pdf", Q_NULLPTR));
        groupBox_17->setTitle(QApplication::translate("MainWindow", "Trier Client :", Q_NULLPTR));
        client_2->setTabText(client_2->indexOf(tab_5), QApplication::translate("MainWindow", "Trier", Q_NULLPTR));
        statClient_2->setText(QApplication::translate("MainWindow", "executer statistique", Q_NULLPTR));
        groupBox_18->setTitle(QApplication::translate("MainWindow", "Statistique :", Q_NULLPTR));
        client_2->setTabText(client_2->indexOf(tab_6), QApplication::translate("MainWindow", "Statistique", Q_NULLPTR));
        sendBtn_2->setText(QApplication::translate("MainWindow", "Send", Q_NULLPTR));
        groupBox_11->setTitle(QApplication::translate("MainWindow", "Mailing :", Q_NULLPTR));
        browseBtnClient->setText(QApplication::translate("MainWindow", "Browse ...", Q_NULLPTR));
        fileClient->setPlaceholderText(QApplication::translate("MainWindow", "attachement here", Q_NULLPTR));
        mail_passClient->setPlaceholderText(QApplication::translate("MainWindow", "your mail password", Q_NULLPTR));
        rcptClient->setPlaceholderText(QApplication::translate("MainWindow", "recipient", Q_NULLPTR));
        msgClient->setPlaceholderText(QApplication::translate("MainWindow", "type your message here ...", Q_NULLPTR));
        subjectClient->setPlaceholderText(QApplication::translate("MainWindow", "subject", Q_NULLPTR));
        sendBtn_Client->setText(QApplication::translate("MainWindow", "Send", Q_NULLPTR));
        client_2->setTabText(client_2->indexOf(tab_7), QApplication::translate("MainWindow", "Email", Q_NULLPTR));
        groupBox_19->setTitle(QApplication::translate("MainWindow", "Image :", Q_NULLPTR));
        groupBox_20->setTitle(QApplication::translate("MainWindow", "Appareil Photo:", Q_NULLPTR));
        cameraClient_2->setText(QApplication::translate("MainWindow", "Camera", Q_NULLPTR));
        groupBox_21->setTitle(QApplication::translate("MainWindow", "Insertion d'image :", Q_NULLPTR));
        playClient_2->setText(QApplication::translate("MainWindow", "play", Q_NULLPTR));
        stopClient_2->setText(QApplication::translate("MainWindow", "stop", Q_NULLPTR));
        client_2->setTabText(client_2->indexOf(tab_8), QApplication::translate("MainWindow", "Image", Q_NULLPTR));
        client->setTabText(client->indexOf(tab_2), QApplication::translate("MainWindow", "Email", Q_NULLPTR));
        groupBox_8->setTitle(QApplication::translate("MainWindow", "Image :", Q_NULLPTR));
        groupBox_9->setTitle(QApplication::translate("MainWindow", "Appareil Photo:", Q_NULLPTR));
        cameraClient->setText(QApplication::translate("MainWindow", "Camera", Q_NULLPTR));
        groupBox_10->setTitle(QApplication::translate("MainWindow", "Insertion d'image :", Q_NULLPTR));
        playClient->setText(QApplication::translate("MainWindow", "play", Q_NULLPTR));
        stopClient->setText(QApplication::translate("MainWindow", "stop", Q_NULLPTR));
        client->setTabText(client->indexOf(tab_4), QApplication::translate("MainWindow", "Image", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
